/*
  n8n Code Node — "Append Row to Confluence Table"
  
  Place this AFTER the HTTP Request GET node (which fetches the current page).
  It takes the existing page XHTML and appends the new table row.
  
  Input: 
    - $('Build Row').item.json.new_row  → the <tr> to append
    - $json  → the GET response from Confluence (contains version + body)
  
  Output: Final PUT body ready to send to Confluence
*/

const items = $input.all();
const item = items[0];

// Current page data from GET response
const currentVersion = item.json.version?.number || 1;
const currentBody = item.json.body?.storage?.value || '';
const pageId = $('Build Row').item.json.page_id || '688129';
const newRow = $('Build Row').item.json.new_row;

let updatedBody;

// Check if table already exists on the page
if (currentBody.includes('<table>') || currentBody.includes('<table ')) {
    // Append new row before the closing </tbody> or </table>
    if (currentBody.includes('</tbody>')) {
        updatedBody = currentBody.replace('</tbody>', `${newRow}\n</tbody>`);
    } else {
        updatedBody = currentBody.replace('</table>', `${newRow}\n</table>`);
    }
} else {
    // Table doesn't exist yet — create fresh table with headers + first row
    updatedBody = `
<h2>Database Changes Log</h2>
<table>
  <tbody>
    <tr>
      <th><p><strong>User Story</strong></p></th>
      <th><p><strong>User Name</strong></p></th>
      <th><p><strong>PR</strong></p></th>
      <th><p><strong>Pkg Changes (DB Scripts)</strong></p></th>
      <th><p><strong>Reviewer</strong></p></th>
    </tr>
    ${newRow}
  </tbody>
</table>
<p><em>Auto-generated by Agentic Documentation System on every PR merge to main.</em></p>
`;
}

// Build the final PUT body
item.json.put_body = {
    id: pageId,
    status: 'current',
    title: 'PI DB Changes - Automated Log',
    body: {
        representation: 'storage',
        value: updatedBody
    },
    version: {
        number: currentVersion + 1,
        message: `Auto-updated: PR merged by ${$('Build Row').item.json.jira_id}`
    }
};

return items;
